name: 'Publishes commit id to ParadoxGamConverters.com'
description: 'Publishes commit ids to ParadoxGamConverters.com for detecting current builds'
inputs:
  destination_file:
    description: 'The file to hold the commit id'
    required: false
  user_email:
    description: 'Email for the git commit'
    required: true
  user_name:
    description: 'GitHub username for the commit'
    required: true
  destination_branch:
    description: 'branch to push file to, defaults to main'
    required: false
  destination_branch_create:
    description: 'Destination branch to create for this main'
    required: false
  commit_message:
    description: 'A custom message for the commmit'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.destination-file }}
    - ${{ inputs.user-email }}
    - ${{ inputs.destination-branch }}
    - ${{ inputs.destination-branch-create }}
    - ${{ inputs.commit-message }}
branding:
  icon: 'git-commit'
  color: 'green'
